"""empty message

Revision ID: 51f7e6ea4c34
Revises: d3128218578d
Create Date: 2019-05-04 10:41:32.271809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51f7e6ea4c34'
down_revision = 'd3128218578d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
