"""empty message

Revision ID: d86d70b9d0ee
Revises: 18325c98cd90
Create Date: 2019-05-03 18:58:23.319222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86d70b9d0ee'
down_revision = '18325c98cd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
